server:
  port: 8001 #服务端口 ​

devtools:
   restart:
     enabled: true #是否支持热部署​

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.springcloud.entities  #所有entity别名所在包

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # zipkin链路监控
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率介于1 到0 之间,1则表示全部采集

eureka:
  client:
    #表示是否向注册中心注册自己
    register-with-eureka: true
    #false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    #访问路径可以显示ip
    prefer-ip-address: true
    #Eureka客户端想服务端发送心跳的时间间隔,单位为秒
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限,单位为秒,超时将删除服务
    lease-expiration-duration-in-seconds: 2