server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称,用于与binding整合
          type: rabbit #消息组建类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: 192.168.244.3
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名字 input 消费者
          destination: studyExchange #表示要使用的Exchange名称定义
          content-tyep: application/json #设置消息类型,本次为json,文本则设置"text/plain"
          binder: defaultRabbit #设置要绑定的消息服务的具体设置  报错没关系
          #group: demoA


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: stream8802
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔 默认30秒
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5s间隔,则移除服务