server:
  port: 800


eureka:
  client:
    register-with-eureka: false
    #fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com/eureka/,http://eureka7002.com:7002/eureka/

#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000


feign:
  hystrix:
    enabled: true   #微服务作为消费方,openfeign想要使用hystrix熔断机制,需要再yml中配置