server:
  port: 9004


spring:
  application:
    name: cloudalibaba-paymentsentinel-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


management:
  endpoints:
    web:
      exposure:
        include: '*'