server:
  port: 800


spring:
  application:
    name: cloud-consumer-order
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #consul 注册中心
  cloud:
    consul:
      discovery:
        service-name:${spring.application.name}
      host: localhost
      port: 8500
