server:
  port: 800

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # zipkin链路监控
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率介于1 到0 之间,1则表示全部采集
  application:
    name: consumer-feign

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com/eureka/,http://eureka7002.com:7002/eureka/



ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.demo.springcloud.feign.PaymentFeignService: debug