server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route   #路由的id,没有固定规则,但要起唯一,建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service     #为了多台service轮流访问,在eureka中注册的名字
          predicates:
            - Path=/payment/get/**          #断言,路径匹配的进行路由

        - id: payment_routh2 #payment_route   #路由的id,没有固定规则,但要起唯一,建议配合服务名
          #uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:         #断言
            - Path=/payment/lb/**          #断言,路径匹配的进行路由
            - After=2021-03-19T21:53:10.858+08:00[Asia/Shanghai] #在这个时间之后,访问lb才能访问
            #- Before=2021-03-19T22:53:10.858+08:00[Asia/Shanghai]
            #- Between=2021-03-19T22:53:10.858+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy   #请求中必须带有cookie ,username为zzyy  cmd中 curl http://localhost:9527/payment/lb --cookie "username=zzyy"
            #- Header=X-Request-Id, \d+    #请求头要有X-Request-Id属性并且值为整数的正则表达式   curl http://localhost:9527/payment/lb  -H "X-Request-Id:123"
            #- Host=**.demo.com
            #- Method=GET
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka

